# agents/ppt_agent.py
"""
PPT (POWERPOINT) AGENT
======================
RESPONSIBILITY: Generates PowerPoint presentation files.

PURPOSE:
- Converts slide structures into actual .pptx files
- Handles file creation and saving to outputs directory
- Operates asynchronously via message queue

INPUT:
- Receives messages from ppt_queue
- Message payload contains:
  * title: Main presentation title
  * slides: List of slide objects with titles and bullets
  * filename: Desired output filename

OUTPUT:
- Saves .pptx files to outputs/ directory
- Notifies result_queue when complete

SLIDE STRUCTURE:
- Title slide (slide 0): Main title + subtitle
- Content slides (slide 1 layout): Title + bullet points
- Supports both new mode (slide objects) and legacy mode (bullet lists)

USAGE:
- Runs continuously as background task
- Processes PPT generation requests from Planner
- Does not interact directly with user
"""

import asyncio
from pathlib import Path
from pptx import Presentation
from queues.message_bus import ppt_queue, result_queue

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

async def ppt_agent():
    print("[PPT Agent] Started.")

    while True:
        msg = await ppt_queue.get()

        if not isinstance(msg, dict) or msg.get("to") != "ppt":
            ppt_queue.task_done()
            continue

        task_id = msg.get("id", "unknown")
        payload = msg.get("payload", {})
        
        # Main presentation title
        main_title = payload.get("title", "Generated Presentation")
        requested_filename = payload.get("filename")

        # Two modes: 
        # 1. "slides" list provided (new mode)
        # 2. "bullets" list provided (legacy mode)
        slides_data = payload.get("slides", [])
        legacy_bullets = payload.get("bullets", [])

        try:
            prs = Presentation()

            # 1. Create Main Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = main_title
            # Optional: Add subtitle if available, else blank
            if slide.placeholders[1]:
                slide.placeholders[1].text = "Generated by Agentic System"

            # 2. Add Content Slides
            if slides_data:
                # NEW MODE: Iterate over slide objects
                bullet_slide_layout = prs.slide_layouts[1]
                
                for slide_info in slides_data:
                    if not isinstance(slide_info, dict):
                        continue
                        
                    s_title = slide_info.get("title", "Topic")
                    s_bullets = slide_info.get("bullets", [])
                    
                    slide = prs.slides.add_slide(bullet_slide_layout)
                    slide.shapes.title.text = str(s_title)
                    
                    # Add bullets
                    if s_bullets:
                        tf = slide.placeholders[1].text_frame
                        tf.clear() # clear default placeholder Text
                        
                        # First bullet
                        tf.text = str(s_bullets[0])
                        
                        # Subsequent bullets
                        for b in s_bullets[1:]:
                            p = tf.add_paragraph()
                            p.text = str(b)
                            p.level = 0 

            elif legacy_bullets:
                # LEGACY MODE: Put all bullets on one slide (or rudimentary split)
                # For backward compatibility, we keep the single slide behavior 
                # or maybe split if too long, but let's stick to original behavior for now.
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                slide.shapes.title.text = "Key Points"
                
                tf = slide.placeholders[1].text_frame
                tf.clear()
                
                if legacy_bullets:
                    tf.text = str(legacy_bullets[0])
                    for b in legacy_bullets[1:]:
                        p = tf.add_paragraph()
                        p.text = str(b)
                        p.level = 0

            # 3. Save File
            if requested_filename:
                safe_name = Path(requested_filename).name
                if not safe_name.lower().endswith(".pptx"):
                    safe_name += ".pptx"
            else:
                safe_name = f"{task_id}.pptx"

            out_path = OUTPUT_DIR / safe_name
            prs.save(out_path)
            
            # Optional: Signal success if needed, but planner usually polls for file existence
            # print(f"[PPT Agent] Created {out_path}")

        except Exception as e:
            error_msg = f"PPT generation failed: {type(e).__name__}: {e}"
            print(f"[PPT Agent] Error: {error_msg}")
            await result_queue.put({
                "id": task_id,
                "from": "ppt",
                "type": "error",
                "content": error_msg
            })

        ppt_queue.task_done()
        await asyncio.sleep(0)
